// Style Metadata Registry - lightweight catalog data for list views and SEO

import type { StyleMeta } from "./meta-types";

/**
 * Static metadata for all styles
 * Extracted from individual style files to avoid bundling full definitions
 */
export const stylesMeta: StyleMeta[] = [
  {
    slug: "neo-brutalist",
    name: "新野兽派",
    nameEn: "Neo-Brutalist",
    description: "大胆的黑色粗边框、硬边缘阴影、无圆角、高对比度配色。源于建筑野兽派，强调功能与原始美学。包含经典、柔和、俏皮三种变体。",
    cover: "/styles/neo-brutalist.svg",
    styleType: "visual",
    tags: ["high-contrast"],
    category: "expressive",
    colors: {
      primary: "#000000",
      secondary: "#ffffff",
      accent: ["#ff006e", "#ccff00", "#00d9ff", "#ff9500"],
    },
    keywords: ["粗边框", "硬阴影", "无圆角", "高对比", "功能主义", "柔和野兽派", "俏皮野兽派"],
  },
  {
    slug: "editorial",
    name: "编辑杂志风",
    nameEn: "Editorial",
    description: "优雅的杂志排版风格，衬线标题、无衬线正文、精致的留白和网格系统。灵感来自高端时尚杂志和报纸排版。",
    cover: "/styles/editorial.svg",
    styleType: "visual",
    tags: [],
    category: "minimal",
    colors: {
      primary: "#0a0a0a",
      secondary: "#fafafa",
      accent: ["#e63946", "#6b7280", "#e5e5e5"],
    },
    keywords: ["杂志排版", "衬线字体", "优雅留白", "网格系统", "极简主义"],
  },
  {
    slug: "neumorphism",
    name: "新拟物派",
    nameEn: "Neumorphism",
    description: "柔和的内凹外凸立体效果，通过双重阴影模拟光源，浅色背景配同色系元素，营造精致的立体感。",
    cover: "/styles/neumorphism.svg",
    styleType: "visual",
    tags: [],
    category: "modern",
    colors: {
      primary: "#e0e5ec",
      secondary: "#d1d9e6",
      accent: ["#6d5dfc", "#ff6b6b", "#4ecdc4", "#ffe66d"],
    },
    keywords: ["立体感", "双重阴影", "柔和", "浅色系", "内凹外凸"],
  },
  {
    slug: "glassmorphism",
    name: "玻璃拟态",
    nameEn: "Glassmorphism",
    description: "半透明毛玻璃效果，通过 backdrop-blur 模糊背景、柔和边框和微妙阴影，创造现代感十足的层叠界面。",
    cover: "/styles/glassmorphism.svg",
    styleType: "visual",
    tags: ["glassmorphic"],
    category: "modern",
    colors: {
      primary: "rgba(255, 255, 255, 0.25)",
      secondary: "rgba(255, 255, 255, 0.18)",
      accent: ["#667eea", "#764ba2", "#f093fb", "#f5576c"],
    },
    keywords: ["毛玻璃", "透明", "模糊", "现代", "层叠"],
  },
  {
    slug: "bento-grid",
    name: "便当盒布局",
    nameEn: "Bento Grid",
    description: "灵感源于日式便当盒的不规则网格布局，通过大小不一的卡片组合创造视觉层次，常用于作品集和产品展示。",
    cover: "/styles/bento-grid.svg",
    styleType: "layout",
    tags: ["responsive"],
    category: "modern",
    colors: {
      primary: "#18181b",
      secondary: "#fafafa",
      accent: ["#3b82f6", "#8b5cf6", "#ec4899", "#f97316"],
    },
    keywords: ["网格", "卡片", "不规则", "作品集", "现代"],
    compatibleWith: ["glassmorphism", "neo-brutalist", "editorial", "neumorphism"],
  },
  {
    slug: "corporate-clean",
    name: "企业简洁风",
    nameEn: "Corporate Clean",
    description: "专业简洁的企业风格，强调可读性、一致性和信任感。适合B2B SaaS、企业官网、后台管理系统。",
    cover: "/styles/corporate-clean.svg",
    styleType: "visual",
    tags: [],
    category: "minimal",
    colors: {
      primary: "#1e40af",
      secondary: "#f8fafc",
      accent: ["#3b82f6", "#64748b", "#10b981"],
    },
    keywords: ["企业", "专业", "简洁", "B2B", "SaaS", "后台", "Dashboard"],
  },
  {
    slug: "minimalist-flat",
    name: "极简扁平风",
    nameEn: "Minimalist Flat",
    description: "极致简约的扁平设计，无阴影无渐变，通过颜色和留白创造层次。适合作品集、创意机构、艺术网站。",
    cover: "/styles/minimalist-flat.svg",
    styleType: "visual",
    tags: [],
    category: "minimal",
    colors: {
      primary: "#000000",
      secondary: "#ffffff",
      accent: ["#ff3366", "#00d4aa", "#ffcc00"],
    },
    keywords: ["极简", "扁平", "无阴影", "作品集", "创意", "艺术"],
  },
  {
    slug: "soft-ui",
    name: "柔和界面风",
    nameEn: "Soft UI",
    description: "温和友好的界面风格，柔和的阴影、圆润的边角、低饱和度的配色。适合消费类应用、社交产品、生活服务类 App。",
    cover: "/styles/soft-ui.svg",
    styleType: "visual",
    tags: [],
    category: "modern",
    colors: {
      primary: "#6366f1",
      secondary: "#f1f5f9",
      accent: ["#ec4899", "#10b981", "#f59e0b"],
    },
    keywords: ["柔和", "圆润", "友好", "消费类", "App", "社交", "生活服务"],
  },
  {
    slug: "natural-organic",
    name: "自然有机风",
    nameEn: "Natural Organic",
    description: "温暖自然的有机风格，大地色系、自然纹理、手工感元素。适合健康品牌、有机食品、环保产品、手工艺品。",
    cover: "/styles/natural-organic.svg",
    styleType: "visual",
    tags: [],
    category: "minimal",
    colors: {
      primary: "#5c4033",
      secondary: "#faf6f1",
      accent: ["#8b9d77", "#d4a373", "#e9e0d4"],
    },
    keywords: ["自然", "有机", "大地色", "手工", "健康", "环保", "可持续"],
  },
  {
    slug: "modern-gradient",
    name: "现代渐变风",
    nameEn: "Modern Gradient",
    description: "充满活力的现代渐变风格，多彩渐变背景、玻璃质感卡片、动态光影效果。适合创业公司、数字产品、活动页面。",
    cover: "/styles/modern-gradient.svg",
    styleType: "visual",
    tags: ["colorful", "gradient"],
    category: "expressive",
    colors: {
      primary: "#8b5cf6",
      secondary: "#1e1b4b",
      accent: ["#06b6d4", "#ec4899", "#f59e0b"],
    },
    keywords: ["渐变", "现代", "活力", "创业", "数字", "动态", "科技感"],
  },
  {
    slug: "retro-vintage",
    name: "复古怀旧风",
    nameEn: "Retro Vintage",
    description: "怀旧复古的设计风格，老式排版、复古色调、手工质感元素。适合咖啡馆、复古品牌、独立杂志、音乐厂牌。",
    cover: "/styles/retro-vintage.svg",
    styleType: "visual",
    tags: ["retro", "texture-heavy"],
    category: "retro",
    colors: {
      primary: "#8b4513",
      secondary: "#f5e6d3",
      accent: ["#c94c4c", "#2e4a3f", "#d4a373"],
    },
    keywords: ["复古", "怀旧", "老式", "手工", "咖啡馆", "独立", "文艺"],
  },
  {
    slug: "dark-mode",
    name: "暗黑模式",
    nameEn: "Dark Mode",
    description: "优雅的深色界面设计，低对比度层次、微妙的边框和高亮。适合开发工具、专业应用、深夜阅读模式。",
    cover: "/styles/dark-mode.svg",
    styleType: "visual",
    tags: ["dark-theme"],
    category: "modern",
    colors: {
      primary: "#3b82f6",
      secondary: "#0f172a",
      accent: ["#22c55e", "#f59e0b", "#ef4444"],
    },
    keywords: ["暗黑", "深色", "夜间", "开发", "专业", "护眼"],
  },
  {
    slug: "macos-vibrancy",
    name: "macOS 毛玻璃",
    nameEn: "macOS Vibrancy",
    description: "macOS 原生暗色毛玻璃风格。通过多层深灰面板、系统级 backdrop-blur 和极度克制的装饰，还原桌面应用的沉稳质感。",
    cover: "/styles/macos-vibrancy.svg",
    styleType: "visual",
    tags: ["dark-theme", "glassmorphic"],
    category: "modern",
    colors: {
      primary: "#3a3a3c",
      secondary: "#1c1c1e",
      accent: ["#0a84ff", "#30d158", "#ff9f0a", "#ff453a"],
    },
    keywords: ["macOS", "原生", "暗色", "毛玻璃", "桌面", "vibrancy", "侧边栏"],
  },
  {
    slug: "geometric-bold",
    name: "几何大胆风",
    nameEn: "Geometric Bold",
    description: "大胆的几何图形设计，强烈的形状对比、鲜明的色块、动态的构图。适合艺术展览、设计机构、创意品牌。",
    cover: "/styles/geometric-bold.svg",
    styleType: "visual",
    tags: ["high-contrast", "colorful", "geometric"],
    category: "expressive",
    colors: {
      primary: "#000000",
      secondary: "#ffffff",
      accent: ["#ff0000", "#0000ff", "#ffff00"],
    },
    keywords: ["几何", "大胆", "色块", "艺术", "创意", "设计", "先锋"],
  },
  // 新增布局风格
  {
    slug: "masonry-flow",
    name: "瀑布流布局",
    nameEn: "Masonry Flow",
    description: "Pinterest 风格的不等高卡片瀑布流布局，通过 CSS columns 或 masonry grid 实现自然流动的视觉效果，适合图片展示、作品集、社交媒体。",
    cover: "/styles/masonry-flow.svg",
    styleType: "layout",
    tags: ["responsive"],
    category: "modern",
    colors: {
      primary: "#1a1a2e",
      secondary: "#f5f5f5",
      accent: ["#e94560", "#16c79a", "#ffd460", "#7579e7"],
    },
    keywords: ["瀑布流", "Pinterest", "不等高", "图片墙", "作品集", "gallery"],
    compatibleWith: ["glassmorphism", "minimalist-flat", "soft-ui", "natural-organic", "editorial"],
  },
  {
    slug: "split-screen",
    name: "分屏布局",
    nameEn: "Split Screen",
    description: "左右对称或不对称的分屏布局，通过对比和平衡创造视觉张力，常用于产品展示、品牌故事、比较页面。",
    cover: "/styles/split-screen.svg",
    styleType: "layout",
    tags: ["responsive"],
    category: "modern",
    colors: {
      primary: "#0f0f0f",
      secondary: "#ffffff",
      accent: ["#ff4757", "#2ed573", "#1e90ff", "#ffa502"],
    },
    keywords: ["分屏", "对比", "左右布局", "对称", "品牌", "展示"],
    compatibleWith: ["neo-brutalist", "minimalist-flat", "editorial", "modern-gradient", "geometric-bold"],
  },
  {
    slug: "full-page-scroll",
    name: "全屏滚动布局",
    nameEn: "Full Page Scroll",
    description: "每一屏占满整个视口的沉浸式滚动体验，通过滚动切换完整场景，适合品牌故事、产品介绍、作品集展示。",
    cover: "/styles/full-page-scroll.svg",
    styleType: "layout",
    tags: [],
    category: "expressive",
    colors: {
      primary: "#000000",
      secondary: "#ffffff",
      accent: ["#6366f1", "#ec4899", "#14b8a6", "#f59e0b"],
    },
    keywords: ["全屏", "滚动", "沉浸式", "场景", "品牌", "故事"],
    compatibleWith: ["glassmorphism", "modern-gradient", "cyberpunk-neon", "minimalist-flat", "geometric-bold"],
  },
  {
    slug: "timeline-vertical",
    name: "垂直时间线布局",
    nameEn: "Vertical Timeline",
    description: "垂直时间轴布局，通过连接线串联时间节点，适合展示历史进程、项目里程碑、工作经历、流程步骤。",
    cover: "/styles/timeline-vertical.svg",
    styleType: "layout",
    tags: [],
    category: "minimal",
    colors: {
      primary: "#1e293b",
      secondary: "#f8fafc",
      accent: ["#3b82f6", "#10b981", "#f59e0b", "#ef4444"],
    },
    keywords: ["时间线", "历程", "里程碑", "流程", "步骤", "进度"],
    compatibleWith: ["editorial", "corporate-clean", "minimalist-flat", "soft-ui", "natural-organic"],
  },
  {
    slug: "card-stack",
    name: "卡片堆叠布局",
    nameEn: "Card Stack",
    description: "卡片前后重叠的立体布局，通过 Z 轴层叠和偏移创造深度感，适合轮播、步骤展示、卡组选择。",
    cover: "/styles/card-stack.svg",
    styleType: "layout",
    tags: [],
    category: "expressive",
    colors: {
      primary: "#1a1a2e",
      secondary: "#f0f0f5",
      accent: ["#6c5ce7", "#00cec9", "#fd79a8", "#ffeaa7"],
    },
    keywords: ["卡片", "堆叠", "立体", "层叠", "轮播", "3D"],
    compatibleWith: ["glassmorphism", "neumorphism", "soft-ui", "modern-gradient", "neo-brutalist"],
  },
  {
    slug: "sidebar-fixed",
    name: "固定侧边栏布局",
    nameEn: "Fixed Sidebar",
    description: "固定位置的侧边导航栏与可滚动主内容区的应用布局，适合后台管理、文档站点、仪表盘、SaaS 应用。",
    cover: "/styles/sidebar-fixed.svg",
    styleType: "layout",
    tags: ["responsive"],
    category: "modern",
    colors: {
      primary: "#1e293b",
      secondary: "#f8fafc",
      accent: ["#3b82f6", "#10b981", "#f59e0b", "#ef4444"],
    },
    keywords: ["侧边栏", "后台", "管理", "导航", "仪表盘", "应用"],
    compatibleWith: ["corporate-clean", "soft-ui", "dark-mode", "minimalist-flat", "neumorphism"],
  },
  {
    slug: "magazine-grid",
    name: "杂志网格布局",
    nameEn: "Magazine Grid",
    description: "灵感来自印刷杂志的多栏网格布局，通过不同大小的内容块创造丰富的视觉层次，适合新闻、博客、内容聚合。",
    cover: "/styles/magazine-grid.svg",
    styleType: "layout",
    tags: ["responsive"],
    category: "modern",
    colors: {
      primary: "#1a1a1a",
      secondary: "#fafafa",
      accent: ["#e63946", "#2a9d8f", "#e9c46a", "#264653"],
    },
    keywords: ["杂志", "多栏", "新闻", "博客", "内容", "网格"],
    compatibleWith: ["editorial", "minimalist-flat", "corporate-clean", "retro-vintage", "dark-mode"],
  },
  {
    slug: "hero-fullscreen",
    name: "全屏英雄区布局",
    nameEn: "Fullscreen Hero",
    description: "以全屏大图或视频为背景的英雄区布局，通过震撼的视觉效果抓住注意力，适合品牌展示、产品发布、活动宣传。",
    cover: "/styles/hero-fullscreen.svg",
    styleType: "layout",
    tags: [],
    category: "expressive",
    colors: {
      primary: "#ffffff",
      secondary: "#000000",
      accent: ["#ff6b6b", "#4ecdc4", "#ffe66d", "#6c5ce7"],
    },
    keywords: ["全屏", "英雄区", "大图", "视频", "品牌", "震撼"],
    compatibleWith: ["glassmorphism", "modern-gradient", "cyberpunk-neon", "minimalist-flat", "dark-mode"],
  },
  // 新增视觉风格
  {
    slug: "claymorphism",
    name: "粘土拟态",
    nameEn: "Claymorphism",
    description: "柔软的粘土质感设计，通过超大圆角、内外阴影组合和柔和渐变，创造出可爱的 3D 立体效果，适合儿童应用和趣味产品。",
    cover: "/styles/claymorphism.svg",
    styleType: "visual",
    tags: ["glassmorphic"],
    category: "modern",
    colors: {
      primary: "#f8b4d9",
      secondary: "#fef3c7",
      accent: ["#a7f3d0", "#c4b5fd", "#fcd34d"],
    },
    keywords: ["粘土", "3D", "可爱", "柔软", "圆润", "儿童", "趣味"],
  },
  {
    slug: "notion-style",
    name: "Notion 风格",
    nameEn: "Notion Style",
    description: "极简清爽的文档工具风格，强调内容可读性和功能性，使用微妙的边框、柔和的悬停效果和清晰的文字层级。",
    cover: "/styles/notion-style.svg",
    styleType: "visual",
    tags: ["brand-inspired"],
    category: "minimal",
    colors: {
      primary: "#37352f",
      secondary: "#ffffff",
      accent: ["#2eaadc", "#eb5757", "#0f7b6c"],
    },
    keywords: ["Notion", "文档", "极简", "清爽", "工具", "协作", "笔记"],
  },
  {
    slug: "stripe-style",
    name: "Stripe 风格",
    nameEn: "Stripe Style",
    description: "精致专业的金融科技风格，以 Stripe 紫为主色调，配合渐变网格背景、精致卡片阴影和流畅动画，适合支付产品和开发者工具。",
    cover: "/styles/stripe-style.svg",
    styleType: "visual",
    tags: ["brand-inspired"],
    category: "modern",
    colors: {
      primary: "#635bff",
      secondary: "#0a2540",
      accent: ["#00d4ff", "#7a73ff", "#80e9ff"],
    },
    keywords: ["Stripe", "金融", "支付", "SaaS", "开发者", "专业", "科技"],
  },
  {
    slug: "apple-style",
    name: "Apple 风格",
    nameEn: "Apple Style",
    description: "极致简约的高端设计风格，大量留白、精致圆角、微妙阴影和 SF Pro 风格字体，传达高端科技产品的品质感。",
    cover: "/styles/apple-style.svg",
    styleType: "visual",
    tags: ["brand-inspired"],
    category: "minimal",
    colors: {
      primary: "#000000",
      secondary: "#f5f5f7",
      accent: ["#0071e3", "#34c759", "#ff3b30"],
    },
    keywords: ["Apple", "极简", "高端", "科技", "产品", "留白", "精致"],
  },
  {
    slug: "pixel-art",
    name: "像素艺术风",
    nameEn: "Pixel Art",
    description: "复古 8-bit 像素游戏风格，无圆角、像素化边框、硬边阴影和鲜明的 8-bit 配色，适合游戏、复古应用和独立开发者项目。",
    cover: "/styles/pixel-art.svg",
    styleType: "visual",
    tags: ["retro", "game-ui"],
    category: "retro",
    colors: {
      primary: "#1a1c2c",
      secondary: "#f4f4f4",
      accent: ["#ff004d", "#00e436", "#29adff", "#ffec27"],
    },
    keywords: ["像素", "8-bit", "复古", "游戏", "怀旧", "独立", "retro"],
  },
  // 新增风格 - 批次1
  {
    slug: "vaporwave",
    name: "霓虹复古",
    nameEn: "Neon Retro",
    description: "80-90年代复古未来主义美学，粉紫渐变、霓虹色彩、故障艺术效果。包含蒸汽波、合成波、赛博朋克三种变体。",
    cover: "/styles/vaporwave.svg",
    styleType: "visual",
    tags: ["retro", "high-contrast", "colorful", "gradient"],
    category: "retro",
    colors: {
      primary: "#ff71ce",
      secondary: "#01cdfe",
      accent: ["#05ffa1", "#b967ff", "#fffb96"],
    },
    keywords: ["蒸汽波", "复古未来", "霓虹", "80年代", "故障艺术", "赛博", "合成波", "赛博朋克", "vaporwave", "synthwave", "cyberpunk"],
  },
  {
    slug: "y2k",
    name: "千禧风格",
    nameEn: "Y2K",
    description: "2000年代初的未来主义美学，金属质感、透明塑料、气泡元素、银色和彩虹渐变。",
    cover: "/styles/y2k.svg",
    styleType: "visual",
    tags: ["retro", "colorful", "gradient"],
    category: "retro",
    colors: {
      primary: "#c0c0c0",
      secondary: "#ff69b4",
      accent: ["#00ffff", "#ff00ff", "#87ceeb"],
    },
    keywords: ["Y2K", "千禧", "未来主义", "金属", "透明", "气泡", "2000年代"],
  },
  {
    slug: "memphis",
    name: "孟菲斯风格",
    nameEn: "Memphis",
    description: "80年代意大利设计运动，大胆的几何图形、鲜艳的撞色、不规则形状和有趣的图案。",
    cover: "/styles/memphis.svg",
    styleType: "visual",
    tags: ["retro", "high-contrast", "colorful", "geometric"],
    category: "retro",
    colors: {
      primary: "#ff6b6b",
      secondary: "#feca57",
      accent: ["#48dbfb", "#ff9ff3", "#1dd1a1", "#5f27cd"],
    },
    keywords: ["孟菲斯", "几何", "撞色", "80年代", "波普", "图案", "大胆"],
  },
  {
    slug: "art-deco",
    name: "装饰艺术风格",
    nameEn: "Art Deco",
    description: "1920-30年代的奢华设计风格，几何对称图案、金色装饰、优雅线条和高端质感。",
    cover: "/styles/art-deco.svg",
    styleType: "visual",
    tags: ["retro", "geometric"],
    category: "retro",
    colors: {
      primary: "#d4af37",
      secondary: "#1a1a2e",
      accent: ["#c9a227", "#2d2d44", "#f5f5dc"],
    },
    keywords: ["装饰艺术", "奢华", "金色", "几何", "1920年代", "优雅", "高端"],
  },
  {
    slug: "bauhaus",
    name: "包豪斯风格",
    nameEn: "Bauhaus",
    description: "德国包豪斯学派的设计理念，强调功能主义、几何形式和原色运用，形式追随功能。",
    cover: "/styles/bauhaus.svg",
    styleType: "visual",
    tags: ["high-contrast", "colorful", "geometric"],
    category: "modern",
    colors: {
      primary: "#000000",
      secondary: "#ffffff",
      accent: ["#ff0000", "#ffcc00", "#0000ff"],
    },
    keywords: ["包豪斯", "功能主义", "几何", "原色", "现代主义", "极简"],
  },
  // 新增风格 - 批次2
  {
    slug: "skeuomorphism",
    name: "拟物设计",
    nameEn: "Skeuomorphism",
    description: "模拟真实世界物体的数字设计风格，通过纹理、光影、材质模仿现实物品，带来熟悉感和直觉性体验。",
    cover: "/styles/skeuomorphism.svg",
    styleType: "visual",
    tags: ["retro"],
    category: "retro",
    colors: {
      primary: "#8b7355",
      secondary: "#d4c4a8",
      accent: ["#c9a227", "#5c4033", "#2e5a3c"],
    },
    keywords: ["拟物", "写实", "纹理", "质感", "真实", "3D", "阴影"],
  },
  {
    slug: "swiss-style",
    name: "瑞士国际风格",
    nameEn: "Swiss International",
    description: "源于瑞士的理性主义设计风格，强调网格系统、无衬线字体、清晰层次和客观信息传达，是现代平面设计的基石。",
    cover: "/styles/swiss-style.svg",
    styleType: "visual",
    tags: ["geometric"],
    category: "modern",
    colors: {
      primary: "#000000",
      secondary: "#ffffff",
      accent: ["#ff0000", "#0057b8", "#ffcc00"],
    },
    keywords: ["瑞士", "国际主义", "网格", "Helvetica", "理性", "排版", "极简"],
  },
  {
    slug: "ghibli-style",
    name: "吉卜力风格",
    nameEn: "Ghibli Style",
    description: "灵感源自吉卜力工作室动画的设计风格，温暖柔和的色调、手绘质感、自然元素和梦幻氛围，传递治愈与诗意。",
    cover: "/styles/ghibli-style.svg",
    styleType: "visual",
    tags: ["retro", "hand-drawn"],
    category: "expressive",
    colors: {
      primary: "#7cb9a8",
      secondary: "#f4e4bc",
      accent: ["#e8a87c", "#85cdca", "#c38d94"],
    },
    keywords: ["吉卜力", "宫崎骏", "手绘", "治愈", "自然", "梦幻", "动画"],
  },
  {
    slug: "material-design",
    name: "材料设计",
    nameEn: "Material Design",
    description: "Google 推出的设计系统，基于纸张和墨水的隐喻，强调层次、动效、大胆色彩和响应式交互，是现代移动端设计的标准。",
    cover: "/styles/material-design.svg",
    styleType: "visual",
    tags: ["brand-inspired"],
    category: "modern",
    colors: {
      primary: "#6200ee",
      secondary: "#03dac6",
      accent: ["#ff0266", "#ffde03", "#00c853"],
    },
    keywords: ["Material", "Google", "层次", "动效", "海拔", "涟漪", "卡片"],
  },
  {
    slug: "fluent-design",
    name: "流利设计",
    nameEn: "Fluent Design",
    description: "微软推出的设计系统，融合了光效、深度、动效、材质和缩放五大元素，打造自然直观的跨平台体验。",
    cover: "/styles/fluent-design.svg",
    styleType: "visual",
    tags: ["brand-inspired", "glassmorphic"],
    category: "modern",
    colors: {
      primary: "#0078d4",
      secondary: "#106ebe",
      accent: ["#ffb900", "#e81123", "#00cc6a"],
    },
    keywords: ["Fluent", "微软", "亚克力", "Reveal", "光效", "深度", "动效"],
  },
  // 新增风格 - 批次3（视觉风格）
  {
    slug: "comic-style",
    name: "漫画风格",
    nameEn: "Comic Style",
    description: "灵感源自漫画书和日式漫画的设计风格，浓重的墨线边框、网点填充、对话气泡、动作线和分镜面板布局，充满故事感和视觉冲击力。",
    cover: "/styles/comic-style.svg",
    styleType: "visual",
    tags: ["high-contrast", "hand-drawn"],
    category: "expressive",
    colors: {
      primary: "#1a1a1a",
      secondary: "#ffffff",
      accent: ["#ff3333", "#ffcc00", "#3366ff", "#33cc33"],
    },
    keywords: ["漫画", "manga", "网点", "对话气泡", "分镜", "动作线", "墨线"],
  },
  {
    slug: "sketch-style",
    name: "铅笔手绘风",
    nameEn: "Sketch Style",
    description: "模拟铅笔手绘的设计风格，不规则线条边框、纸张纹理背景、手写字体感、素描阴影和涂鸦装饰，传达亲切温暖的手工质感。",
    cover: "/styles/sketch-style.svg",
    styleType: "visual",
    tags: ["retro", "hand-drawn"],
    category: "expressive",
    colors: {
      primary: "#2c2c2c",
      secondary: "#f5f0e8",
      accent: ["#e74c3c", "#3498db", "#27ae60", "#f39c12"],
    },
    keywords: ["手绘", "铅笔", "素描", "纸张", "手写", "涂鸦", "不规则"],
  },
  {
    slug: "watercolor-style",
    name: "水彩画风",
    nameEn: "Watercolor Style",
    description: "灵感源自水彩画的设计风格，柔和的颜色渐变、模糊的边缘效果、纸张质感背景和流动的色彩扩散，传递艺术感与诗意。",
    cover: "/styles/watercolor-style.svg",
    styleType: "visual",
    tags: ["hand-drawn"],
    category: "expressive",
    colors: {
      primary: "#4a6fa5",
      secondary: "#faf8f5",
      accent: ["#e8a87c", "#85cdca", "#c38d94", "#d4a373"],
    },
    keywords: ["水彩", "渐变", "柔和", "纸张", "艺术", "流动", "诗意"],
  },
  // 新增布局风格 - 批次3
  {
    slug: "f-pattern-layout",
    name: "F型布局",
    nameEn: "F-Pattern Layout",
    description: "基于眼动追踪研究的F型扫描布局，用户视线从左上角开始，沿顶部水平扫描后向下移动，适合内容密集型页面、博客文章和新闻列表。",
    cover: "/styles/f-pattern-layout.svg",
    styleType: "layout",
    tags: ["responsive"],
    category: "modern",
    colors: {
      primary: "#1a1a2e",
      secondary: "#f8f9fa",
      accent: ["#e63946", "#457b9d", "#2a9d8f", "#e9c46a"],
    },
    keywords: ["F型", "眼动", "内容优先", "扫描", "阅读", "博客", "新闻"],
    compatibleWith: ["editorial", "corporate-clean", "minimalist-flat", "notion-style", "swiss-style"],
  },
  {
    slug: "z-pattern-layout",
    name: "Z型布局",
    nameEn: "Z-Pattern Layout",
    description: "基于眼动追踪的Z型扫描布局，视线从左上到右上，斜穿到左下再到右下，形成Z字路径。适合着陆页、营销页面和简洁信息展示。",
    cover: "/styles/z-pattern-layout.svg",
    styleType: "layout",
    tags: ["responsive"],
    category: "modern",
    colors: {
      primary: "#0f172a",
      secondary: "#ffffff",
      accent: ["#6366f1", "#06b6d4", "#f59e0b", "#ec4899"],
    },
    keywords: ["Z型", "着陆页", "营销", "视觉引导", "CTA", "扫描路径"],
    compatibleWith: ["modern-gradient", "apple-style", "stripe-style", "minimalist-flat", "corporate-clean"],
  },
  {
    slug: "holy-grail-layout",
    name: "圣杯布局",
    nameEn: "Holy Grail Layout",
    description: "经典的三栏式网页布局，由固定页头、三列中间区域（左侧导航、主内容、右侧边栏）和固定页脚组成，是Web设计的基础布局范式。",
    cover: "/styles/holy-grail-layout.svg",
    styleType: "layout",
    tags: ["responsive"],
    category: "modern",
    colors: {
      primary: "#1e293b",
      secondary: "#f1f5f9",
      accent: ["#3b82f6", "#10b981", "#f59e0b", "#ef4444"],
    },
    keywords: ["三栏", "圣杯", "经典", "页头", "页脚", "侧边栏", "导航"],
    compatibleWith: ["corporate-clean", "editorial", "notion-style", "minimalist-flat", "dark-mode"],
  },
  {
    slug: "dashboard-layout",
    name: "仪表盘布局",
    nameEn: "Dashboard Layout",
    description: "数据驱动的仪表盘布局，包含侧边导航、顶部工具栏、多模块数据面板和图表区域，适合后台管理系统、数据分析平台和监控面板。",
    cover: "/styles/dashboard-layout.svg",
    styleType: "layout",
    tags: ["responsive"],
    category: "modern",
    colors: {
      primary: "#111827",
      secondary: "#f9fafb",
      accent: ["#6366f1", "#10b981", "#f59e0b", "#ef4444"],
    },
    keywords: ["仪表盘", "数据", "面板", "图表", "监控", "后台", "分析"],
    compatibleWith: ["corporate-clean", "dark-mode", "minimalist-flat", "fluent-design", "material-design"],
  },
  // Previously orphaned styles
  {
    slug: "cyberpunk-neon",
    name: "赛博朋克霓虹",
    nameEn: "Cyberpunk Neon",
    description: "未来感十足的赛博朋克风格，霓虹发光效果、深色背景、高科技感的 UI 元素。适合游戏、科技产品、创意工作室。",
    cover: "/styles/cyberpunk-neon.svg",
    styleType: "visual",
    tags: ["high-contrast", "dark-theme", "colorful"],
    category: "expressive",
    colors: {
      primary: "#00ffff",
      secondary: "#0a0a0f",
      accent: ["#ff00ff", "#ffff00", "#00ff00"],
    },
    keywords: ["赛博朋克", "霓虹", "未来", "发光", "游戏", "科技"],
  },
  {
    slug: "synthwave",
    name: "合成波",
    nameEn: "Synthwave",
    description: "80年代复古未来主义音乐美学，霓虹粉紫配色、网格地平线、日落渐变和复古科技感，充满怀旧的未来想象。",
    cover: "/styles/synthwave.svg",
    styleType: "visual",
    tags: ["retro", "high-contrast", "dark-theme", "colorful", "gradient"],
    category: "retro",
    colors: {
      primary: "#ff00ff",
      secondary: "#00ffff",
      accent: ["#ff6ec7", "#7b68ee", "#ff1493"],
    },
    keywords: ["合成波", "80年代", "霓虹", "复古未来", "网格", "日落"],
  },
  {
    slug: "neo-brutalist-soft",
    name: "柔和野兽派",
    nameEn: "Neo-Brutalist Soft",
    description: "Neo-Brutalist 的温和版本。保留硬边缘阴影和无圆角特性，但使用更柔和的配色、较细的边框和更温和的对比度。",
    cover: "/styles/neo-brutalist-soft.svg",
    styleType: "visual",
    tags: ["high-contrast"],
    category: "expressive",
    colors: {
      primary: "#1a1a1a",
      secondary: "#f5f5f5",
      accent: ["#f472b6", "#a3e635", "#38bdf8", "#fbbf24"],
    },
    keywords: ["柔和野兽派", "温和对比", "浅色阴影", "细边框", "淡彩"],
  },
  {
    slug: "neo-brutalist-playful",
    name: "俏皮野兽派",
    nameEn: "Neo-Brutalist Playful",
    description: "Neo-Brutalist 的活泼版本。保留核心特征，加入更多色彩、旋转倾斜元素和有趣的微交互，适合年轻化品牌。",
    cover: "/styles/neo-brutalist-playful.svg",
    styleType: "visual",
    tags: ["colorful"],
    category: "expressive",
    colors: {
      primary: "#000000",
      secondary: "#ffffff",
      accent: ["#ff6b6b", "#4ecdc4", "#ffe66d", "#95e1d3", "#f38181"],
    },
    keywords: ["俏皮野兽派", "多彩", "倾斜元素", "年轻化"],
  },
  // New styles - Batch 4
  {
    slug: "art-nouveau",
    name: "新艺术运动风",
    nameEn: "Art Nouveau",
    description: "灵感源自19世纪末新艺术运动的设计风格，以有机曲线、藤蔓花卉纹样、自然形态和精致装饰线条为特征，传递优雅与自然的和谐美感。",
    cover: "/styles/art-nouveau.svg",
    styleType: "visual",
    tags: ["retro"],
    category: "retro",
    colors: { primary: "#2d5016", secondary: "#f5f0e1", accent: ["#c9a227", "#8b6db5", "#4a7c59"] },
    keywords: ["新艺术", "有机曲线", "藤蔓", "花卉", "穆夏", "装饰线条"],
  },
  {
    slug: "surrealism",
    name: "超现实主义风",
    nameEn: "Surrealism",
    description: "灵感源自超现实主义艺术运动的设计风格，融合梦境与现实、扭曲空间、不合逻辑的并置和潜意识意象，创造奇幻神秘的视觉体验。",
    cover: "/styles/surrealism.svg",
    styleType: "visual",
    tags: ["retro", "hand-drawn"],
    category: "expressive",
    colors: { primary: "#1a1a3e", secondary: "#f0ece4", accent: ["#d4a574", "#c38d94", "#7b68a8"] },
    keywords: ["超现实", "梦境", "潜意识", "达利", "马格里特", "奇幻"],
  },
  {
    slug: "ukiyo-e-digital",
    name: "浮世绘数字风",
    nameEn: "Ukiyo-e Digital",
    description: "将日本浮世绘版画美学与数字设计融合的风格，扁平色块、精致线描、浮世绘式构图和传统配色，呈现东方古典与现代数字的碰撞。",
    cover: "/styles/ukiyo-e-digital.svg",
    styleType: "visual",
    tags: ["retro"],
    category: "retro",
    colors: { primary: "#1a3055", secondary: "#f5f0e1", accent: ["#d4553a", "#c9a227", "#3d6b8e"] },
    keywords: ["浮世绘", "版画", "日本", "扁平色块", "线描", "葛饰北斋"],
  },
  {
    slug: "gothic",
    name: "哥特式风",
    nameEn: "Gothic",
    description: "灵感源自哥特式建筑与文化的设计风格，深色调、尖拱形态、华丽装饰纹样和神秘氛围，传递庄严肃穆与暗黑浪漫的美学。",
    cover: "/styles/gothic.svg",
    styleType: "visual",
    tags: ["retro", "high-contrast", "dark-theme"],
    category: "retro",
    colors: { primary: "#2d1b4e", secondary: "#0a0a0a", accent: ["#8b1a1a", "#c9a227", "#4a1a4a"] },
    keywords: ["哥特", "暗黑", "尖拱", "华丽", "神秘", "中世纪"],
  },
  {
    slug: "outrun",
    name: "Outrun 复古未来",
    nameEn: "Outrun",
    description: "灵感源自80年代赛车游戏和复古未来主义美学的设计风格，霓虹粉紫、透视网格、日落渐变和高速运动感，营造复古科幻的视觉冲击。",
    cover: "/styles/outrun.svg",
    styleType: "visual",
    tags: ["retro", "high-contrast", "dark-theme", "colorful", "gradient"],
    category: "retro",
    colors: { primary: "#ff006e", secondary: "#0a0a0a", accent: ["#a020f0", "#00d4ff", "#ff6ec7"] },
    keywords: ["Outrun", "复古未来", "霓虹", "网格", "赛车", "80年代"],
  },
  {
    slug: "dark-academia",
    name: "暗黑学院风",
    nameEn: "Dark Academia",
    description: "灵感源自古典学院文化的设计风格，深棕色调、旧书质感、古典排版和学术氛围，传递文学、历史与知识的浪漫情怀。",
    cover: "/styles/dark-academia.svg",
    styleType: "visual",
    tags: ["retro", "dark-theme", "texture-heavy"],
    category: "retro",
    colors: { primary: "#3d2b1f", secondary: "#f5f0e1", accent: ["#2d4a3e", "#8b7355", "#6b4c3b"] },
    keywords: ["暗黑学院", "古典", "文学", "旧书", "学术", "复古"],
  },
  {
    slug: "cottagecore",
    name: "田园核风",
    nameEn: "Cottagecore",
    description: "灵感源自乡村田园生活的设计风格，柔和自然色、花卉纹样、手工质感和温馨舒适的氛围，传递对简单纯粹生活的向往。",
    cover: "/styles/cottagecore.svg",
    styleType: "visual",
    tags: ["retro", "hand-drawn", "texture-heavy"],
    category: "retro",
    colors: { primary: "#5a8f5a", secondary: "#f5f0e1", accent: ["#f5d75f", "#8b7355", "#d4a0a0"] },
    keywords: ["田园", "乡村", "花卉", "手工", "温馨", "自然"],
  },
  {
    slug: "risograph",
    name: "Risograph 印刷风",
    nameEn: "Risograph",
    description: "灵感源自 Risograph 孔版印刷的设计风格，鲜明的专色叠印、半色调网点、轻微的套印偏移和纸张质感，呈现独特的手工印刷美感。",
    cover: "/styles/risograph.svg",
    styleType: "visual",
    tags: ["high-contrast", "texture-heavy"],
    category: "expressive",
    colors: { primary: "#ff6b9d", secondary: "#f5f5f0", accent: ["#2563eb", "#ff8a00", "#22c55e"] },
    keywords: ["Risograph", "孔版印刷", "专色", "叠印", "半色调", "网点"],
  },
  {
    slug: "mecha",
    name: "机甲风",
    nameEn: "Mecha",
    description: "灵感源自日系机甲动画与军事工业设计的风格，钢铁质感、警示标识、技术参数标注和机械结构线条，传递力量感与科技感。",
    cover: "/styles/mecha.svg",
    styleType: "visual",
    tags: ["high-contrast", "dark-theme", "game-ui", "anime-aesthetic"],
    category: "expressive",
    colors: { primary: "#1a2744", secondary: "#e5e5e5", accent: ["#4a5c3a", "#fbbf24", "#ef4444"] },
    keywords: ["机甲", "高达", "军事", "钢铁", "机械", "工业"],
  },
  {
    slug: "gothic-lolita",
    name: "哥特萝莉风",
    nameEn: "Gothic Lolita",
    description: "融合哥特暗黑美学与洛丽塔少女元素的设计风格，深色蕾丝、玫瑰纹样、维多利亚式装饰和精致的对比配色，传递暗黑浪漫的精致感。",
    cover: "/styles/gothic-lolita.svg",
    styleType: "visual",
    tags: ["retro", "dark-theme"],
    category: "expressive",
    colors: { primary: "#4a1a4a", secondary: "#e5e5e5", accent: ["#0a0a0a", "#8b1a2a", "#c9a2c9"] },
    keywords: ["哥特萝莉", "蕾丝", "玫瑰", "维多利亚", "暗黑", "少女"],
  },
  {
    slug: "cyber-chinese",
    name: "赛博中华风",
    nameEn: "Cyber Chinese",
    description: "融合赛博朋克科技感与中华传统美学的设计风格，霓虹灯笼、数字山水、电路纹样与传统元素碰撞，创造东方未来主义的视觉体验。",
    cover: "/styles/cyber-chinese.svg",
    styleType: "visual",
    tags: ["high-contrast", "dark-theme", "anime-aesthetic"],
    category: "expressive",
    colors: { primary: "#d4553a", secondary: "#0a0a0a", accent: ["#c9a227", "#00d4ff", "#a020f0"] },
    keywords: ["赛博中华", "霓虹灯笼", "数字山水", "东方未来", "国潮", "科技国风"],
  },
  // New styles - Batch 5
  {
    slug: "acid-graphics",
    name: "酸性平面设计",
    nameEn: "Acid Graphics",
    description: "高饱和度荧光色彩、扭曲字体、液态流动形态和迷幻视觉。源于锐舞文化和地下俱乐部美学，以强烈的视觉冲击力呈现反叛与实验精神。",
    cover: "/styles/acid-graphics.svg",
    styleType: "visual",
    tags: ["high-contrast", "colorful"],
    category: "expressive",
    colors: { primary: "#39ff14", secondary: "#0a0a0a", accent: ["#e6ff00", "#a020f0", "#ff6ec7"] },
    keywords: ["酸性", "迷幻", "荧光", "扭曲", "液态", "锐舞"],
  },
  {
    slug: "hand-drawn-doodle",
    name: "手绘涂鸦风",
    nameEn: "Hand-Drawn Doodle",
    description: "手绘线条、涂鸦插画、不规则形状和手写字体。像在笔记本上随手画出的设计，充满创意和趣味性，传达温暖亲切的手工感。",
    cover: "/styles/hand-drawn-doodle.svg",
    styleType: "visual",
    tags: ["hand-drawn"],
    category: "expressive",
    colors: { primary: "#2c2c2c", secondary: "#fffef5", accent: ["#ff6b6b", "#4ecdc4", "#ffd93d"] },
    keywords: ["手绘", "涂鸦", "插画", "不规则", "手写", "创意"],
  },
  {
    slug: "swiss-poster",
    name: "瑞士海报风",
    nameEn: "Swiss Poster",
    description: "大胆排版、网格对齐、原色色块和实验性布局。源于瑞士国际主义海报设计传统，以超大字体和强烈的视觉层次构建信息传达。",
    cover: "/styles/swiss-poster.svg",
    styleType: "visual",
    tags: ["high-contrast", "geometric"],
    category: "modern",
    colors: { primary: "#000000", secondary: "#ffffff", accent: ["#ff0000", "#0057b8", "#ffcc00"] },
    keywords: ["海报", "大字体", "网格", "实验排版", "国际主义", "平面设计"],
  },
  {
    slug: "watercolor-art",
    name: "水彩艺术风",
    nameEn: "Watercolor Art",
    description: "真实水彩画美学，柔和的水彩晕染、透明度叠加、纸张质感和艺术笔触，营造出如同水彩画作般的精致视觉体验。",
    cover: "/styles/watercolor-art.svg",
    styleType: "visual",
    tags: ["hand-drawn"],
    category: "expressive",
    colors: { primary: "#d4a0a0", secondary: "#faf8f5", accent: ["#87ceeb", "#98d8c8", "#c3b1e1"] },
    keywords: ["水彩", "晕染", "透明", "纸张", "艺术", "笔触", "留白"],
  },
  {
    slug: "impressionist-oil",
    name: "油画印象派风",
    nameEn: "Impressionist Oil",
    description: "受莫奈、雷诺阿等印象派大师启发，大胆的笔触纹理、光影交织、点彩色彩和温暖的画布质感，呈现如油画般的浓郁视觉体验。",
    cover: "/styles/impressionist-oil.svg",
    styleType: "visual",
    tags: ["retro", "hand-drawn", "texture-heavy"],
    category: "retro",
    colors: { primary: "#e8a87c", secondary: "#f5f0e1", accent: ["#c0392b", "#2c3e50", "#1abc9c"] },
    keywords: ["油画", "印象派", "笔触", "光影", "莫奈", "色彩", "画布"],
  },
  {
    slug: "collage-art",
    name: "拼贴艺术风",
    nameEn: "Collage Art",
    description: "杂志拼贴和混合材料美学，纸片剪切、多层叠加、撕纸边缘和混搭字体，营造充满创意和手工感的视觉冲击。",
    cover: "/styles/collage-art.svg",
    styleType: "visual",
    tags: ["retro", "hand-drawn", "texture-heavy"],
    category: "expressive",
    colors: { primary: "#2d2d2d", secondary: "#f5f0e8", accent: ["#e74c3c", "#3498db", "#f39c12", "#9b59b6"] },
    keywords: ["拼贴", "剪贴", "混合材质", "多层", "杂志", "撕纸", "混搭"],
  },
  {
    slug: "glitch-art",
    name: "故障艺术风",
    nameEn: "Glitch Art",
    description: "数字故障美学风格，通过像素错位、RGB色彩分离、扫描线和数字损坏效果，呈现赛博朋克式的视觉冲击和数据腐蚀质感。",
    cover: "/styles/glitch-art.svg",
    styleType: "visual",
    tags: ["high-contrast"],
    category: "expressive",
    colors: { primary: "#00ffff", secondary: "#0a0a0a", accent: ["#ff00ff", "#ffff00", "#ffffff"] },
    keywords: ["故障", "像素", "RGB分离", "扫描线", "数字损坏", "错位", "glitch"],
  },
  {
    slug: "visual-novel",
    name: "视觉小说风",
    nameEn: "Visual Novel",
    description: "借鉴视觉小说游戏UI的设计风格，半透明对话框、角色立绘、选项按钮和文字动画，打造沉浸式交互故事体验。",
    cover: "/styles/visual-novel.svg",
    styleType: "visual",
    tags: ["dark-theme", "game-ui", "anime-aesthetic"],
    category: "modern",
    colors: { primary: "#4a5568", secondary: "#f7fafc", accent: ["#6366f1", "#ec4899", "#10b981"] },
    keywords: ["视觉小说", "对话框", "立绘", "选项", "游戏UI", "交互故事"],
  },
  {
    slug: "shoujo-manga",
    name: "少女漫画风",
    nameEn: "Shoujo Manga",
    description: "少女漫画特有的浪漫美学，樱花花瓣装饰、闪光效果、柔和流线、爱心元素和粉色主色调，呈现梦幻柔美的视觉体验。",
    cover: "/styles/shoujo-manga.svg",
    styleType: "visual",
    tags: ["retro", "anime-aesthetic"],
    category: "expressive",
    colors: { primary: "#ffb7c5", secondary: "#fff5f7", accent: ["#c4b5fd", "#fde68a", "#fecdd3"] },
    keywords: ["少女漫画", "樱花", "闪光", "花瓣", "爱心", "浪漫", "柔美"],
  },
  {
    slug: "cyber-anime",
    name: "赛博动漫风",
    nameEn: "Cyber Anime",
    description: "融合赛博朋克科幻UI与动漫美学，以深色背景上的霓虹光效、全息投影感和锐利几何线条，打造未来感十足的动漫界面风格。",
    cover: "/styles/cyber-anime.svg",
    styleType: "visual",
    tags: ["high-contrast", "dark-theme", "anime-aesthetic", "game-ui"],
    category: "expressive",
    colors: { primary: "#7c3aed", secondary: "#0f0f1a", accent: ["#06d6a0", "#ff006e", "#38bdf8"] },
    keywords: ["赛博动漫", "科幻UI", "全息", "霓虹", "动漫", "未来"],
  },
  {
    slug: "pixel-anime",
    name: "像素动漫风",
    nameEn: "Pixel Anime",
    description: "将像素艺术的8-bit复古质感与动漫角色美学相融合，呈现出Q版像素角色、游戏UI元素和怀旧色彩的独特风格。",
    cover: "/styles/pixel-anime.svg",
    styleType: "visual",
    tags: ["retro", "dark-theme", "anime-aesthetic", "game-ui"],
    category: "retro",
    colors: { primary: "#4a90d9", secondary: "#2d1b69", accent: ["#ff6b6b", "#ffd93d", "#50c878"] },
    keywords: ["像素动漫", "8-bit", "复古游戏", "Q版", "像素", "怀旧"],
  },
  {
    slug: "japanese-fresh",
    name: "日系清新风",
    nameEn: "Japanese Fresh",
    description: "以淡雅配色、大面积留白和纤细线条为特征的日系清新设计，营造清新治愈、轻盈透气的视觉感受。",
    cover: "/styles/japanese-fresh.svg",
    styleType: "visual",
    tags: [],
    category: "minimal",
    colors: { primary: "#64b5f6", secondary: "#fafaf8", accent: ["#98d8c8", "#ffb7c5", "#b8d4e3"] },
    keywords: ["日系", "清新", "淡雅", "轻量", "简约", "治愈", "生活"],
  },
  {
    slug: "neon-samurai",
    name: "霓虹武士风",
    nameEn: "Neon Samurai",
    description: "日本传统武士美学与霓虹赛博朋克的碰撞融合，刀锋般锐利的线条、汉字书法与霓虹光效交织，浮世绘遇见霓虹灯的未来都市武道。",
    cover: "/styles/neon-samurai.svg",
    styleType: "visual",
    tags: ["high-contrast", "dark-theme", "anime-aesthetic"],
    category: "expressive",
    colors: { primary: "#dc2626", secondary: "#0a0a0a", accent: ["#a020f0", "#38bdf8", "#fbbf24"] },
    keywords: ["霓虹武士", "赛博武士", "日本", "霓虹", "传统融合", "动作"],
  },
  {
    slug: "magic-circle",
    name: "魔法阵风",
    nameEn: "Magic Circle",
    description: "几何魔法阵、神秘符文与光粒子效果的奇幻视觉风格，精密的同心圆纹样、金色辉光与深邃海军蓝底色营造神秘魔法氛围。",
    cover: "/styles/magic-circle.svg",
    styleType: "visual",
    tags: ["dark-theme", "geometric", "anime-aesthetic"],
    category: "expressive",
    colors: { primary: "#1e1b4b", secondary: "#0f0e2e", accent: ["#fbbf24", "#e2e8f0", "#818cf8"] },
    keywords: ["魔法阵", "符文", "神秘", "奇幻", "光效", "几何", "魔法"],
  },
  {
    slug: "cyber-wafuu",
    name: "赛博和风",
    nameEn: "Cyber Wafuu",
    description: "传统和风纹样与未来科技的数字化融合，折纸几何、青海波数字化重构、电路纹路与金箔光泽交织的日式赛博美学。",
    cover: "/styles/cyber-wafuu.svg",
    styleType: "visual",
    tags: ["high-contrast", "dark-theme", "anime-aesthetic"],
    category: "expressive",
    colors: { primary: "#1e3a5f", secondary: "#0a0a14", accent: ["#c41e3a", "#c9a227", "#38bdf8"] },
    keywords: ["赛博和风", "数字和风", "折纸", "日式科技", "传统纹样", "未来"],
  },
  // New styles - Batch 6
  {
    slug: "steampunk",
    name: "蒸汽朋克",
    nameEn: "Steampunk",
    description: "维多利亚时代与工业机械的复古未来主义融合，黄铜齿轮、蒸汽管道、皮革质感和精密仪表盘的美学。",
    cover: "/styles/steampunk.svg",
    styleType: "visual",
    tags: ["retro", "high-contrast", "dark-theme", "texture-heavy"],
    category: "retro",
    colors: { primary: "#2d1810", secondary: "#f4e4bc", accent: ["#b87333", "#8b4513", "#cd853f"] },
    keywords: ["蒸汽朋克", "维多利亚", "齿轮", "黄铜", "机械", "复古未来"],
  },
  {
    slug: "pop-art",
    name: "波普艺术",
    nameEn: "Pop Art",
    description: "安迪沃霍尔式的大胆色彩和半调网点，源自60年代流行文化，高对比度、重复图案和漫画风格的视觉冲击。",
    cover: "/styles/pop-art.svg",
    styleType: "visual",
    tags: ["retro", "high-contrast", "colorful"],
    category: "expressive",
    colors: { primary: "#ff0066", secondary: "#ffff00", accent: ["#00ccff", "#ff6600", "#cc00ff"] },
    keywords: ["波普艺术", "半调网点", "大胆色彩", "流行文化", "漫画风格", "沃霍尔"],
  },
  {
    slug: "solarpunk",
    name: "太阳朋克",
    nameEn: "Solarpunk",
    description: "生态未来主义的乌托邦愿景，融合可持续科技与自然元素，明亮的绿色调、太阳能美学和有机形态。",
    cover: "/styles/solarpunk.svg",
    styleType: "visual",
    tags: [],
    category: "modern",
    colors: { primary: "#2d6a4f", secondary: "#f0fdf4", accent: ["#fbbf24", "#22c55e", "#0ea5e9"] },
    keywords: ["太阳朋克", "生态未来", "可持续", "绿色科技", "乌托邦", "自然"],
  },
  {
    slug: "jrpg",
    name: "日式RPG",
    nameEn: "JRPG",
    description: "经典日式角色扮演游戏的UI美学，华丽的边框装饰、魔法效果、状态面板和幻想风格的视觉元素。",
    cover: "/styles/jrpg.svg",
    styleType: "visual",
    tags: ["retro", "high-contrast", "dark-theme", "anime-aesthetic", "game-ui"],
    category: "expressive",
    colors: { primary: "#1a1a2e", secondary: "#eef2ff", accent: ["#fbbf24", "#8b5cf6", "#ef4444"] },
    keywords: ["JRPG", "角色扮演", "游戏UI", "幻想", "魔法", "状态面板"],
  },
  {
    slug: "asymmetric-grid",
    name: "非对称网格",
    nameEn: "Asymmetric Grid",
    description: "打破传统对称网格的布局方式，通过不规则的列宽、重叠元素和视觉张力创造动态有趣的页面结构。",
    cover: "/styles/asymmetric-grid.svg",
    styleType: "layout",
    tags: ["high-contrast"],
    compatibleWith: ["editorial", "neo-brutalist", "geometric-bold", "swiss-style"],
    category: "modern",
    colors: { primary: "#0f0f0f", secondary: "#ffffff", accent: ["#ff3366", "#00d4ff", "#ffcc00"] },
    keywords: ["非对称", "网格", "不规则", "动态", "张力", "重叠", "创意"],
  },
  {
    slug: "parallax-sections",
    name: "视差滚动",
    nameEn: "Parallax Sections",
    description: "通过固定背景和滚动内容创造深度视差效果的沉浸式布局，每个全屏区块都有独立的背景层。",
    cover: "/styles/parallax-sections.svg",
    styleType: "layout",
    tags: ["responsive"],
    compatibleWith: ["hero-fullscreen", "full-page-scroll", "editorial", "modern-gradient"],
    category: "modern",
    colors: { primary: "#1e3a5f", secondary: "#f8fafc", accent: ["#3b82f6", "#93c5fd", "#0ea5e9"] },
    keywords: ["视差", "滚动", "深度", "层次", "沉浸", "固定背景", "全屏"],
  },
  // New styles - Batch 7
  {
    slug: "warm-dashboard",
    name: "暖色仪表盘",
    nameEn: "Warm Dashboard",
    description: "温暖柔和的仪表盘设计风格，采用珊瑚/赤陶色背景、奶油白卡片、柔和阴影，营造舒适专业的数据展示体验。",
    cover: "/styles/warm-dashboard.svg",
    styleType: "visual",
    tags: [],
    category: "modern",
    colors: {
      primary: "#d4a088",
      secondary: "#faf8f5",
      accent: ["#4a9d9a", "#e8b86d", "#c17767", "#6b8e8e"],
    },
    keywords: ["暖色", "仪表盘", "珊瑚色", "赤陶", "奶油白", "数据可视化", "舒适"],
  },
  {
    slug: "neon-gradient",
    name: "霓虹渐变",
    nameEn: "Neon Gradient",
    description: "深色背景上的鲜艳渐变卡片，配合粗彩色边框和霓虹发光效果，适合科技产品、SaaS 着陆页、年轻化品牌。",
    cover: "/styles/neon-gradient.svg",
    styleType: "visual",
    tags: ["dark-theme", "gradient"],
    category: "expressive",
    colors: {
      primary: "#a855f7",
      secondary: "#0f0a1e",
      accent: ["#f472b6", "#22d3ee", "#a3e635", "#fbbf24", "#fb7185"],
    },
    keywords: ["霓虹", "渐变", "深色", "发光", "科技", "SaaS", "年轻化"],
  },
  // New styles - Batch 8
  {
    slug: "liquid-glass",
    name: "Apple 流动玻璃",
    nameEn: "Apple Liquid Glass",
    description: "Apple WWDC 2025 发布的全新设计语言，通过 SVG 折射滤镜、彩虹边缘光晕、流体形变动画和多层玻璃堆叠，创造出超越传统毛玻璃的有机流动视觉体验。",
    cover: "/styles/liquid-glass.svg",
    styleType: "visual",
    tags: ["brand-inspired"],
    category: "modern",
    colors: {
      primary: "rgba(255, 255, 255, 0.1)",
      secondary: "rgba(255, 255, 255, 0.15)",
      accent: ["#ff6b6b", "#4ecdc4", "#a855f7", "#007AFF", "#FF2D55"],
    },
    keywords: ["Apple", "Liquid Glass", "流动玻璃", "彩虹边缘", "折射", "多层堆叠", "WWDC 2025"],
  },
  // New styles - from style-optimization
  {
    slug: "scandinavian",
    name: "北欧极简风",
    nameEn: "Scandinavian Minimalism",
    description: "源自北欧的温暖极简设计，强调自然材质、舒适留白、木质色调和Hygge生活美学，营造宁静温馨的视觉体验。",
    cover: "/styles/scandinavian.jpg",
    styleType: "visual",
    tags: [],
    category: "minimal",
    colors: {
      primary: "#3d3d3d",
      secondary: "#f5f0eb",
      accent: ["#5a7a6b", "#7ba0b8", "#c9a88c"],
    },
    keywords: ["北欧", "斯堪的纳维亚", "Hygge", "木质", "自然", "温暖", "留白", "舒适"],
  },
  {
    slug: "cel-shading",
    name: "赛璐璐动画风",
    nameEn: "Cel Shading",
    description: "模拟传统动画赛璐璐片的渲染风格，粗黑轮廓线、平面色块填充、无渐变阴影和鲜艳饱和色彩，充满卡通游戏的活力感。",
    cover: "/styles/cel-shading.jpg",
    styleType: "visual",
    tags: ["high-contrast", "game-ui", "anime-aesthetic"],
    category: "expressive",
    colors: {
      primary: "#1a1a2e",
      secondary: "#fafaf5",
      accent: ["#e63946", "#4ea8de", "#2ecc71", "#f1c40f"],
    },
    keywords: ["赛璐璐", "卡通", "轮廓线", "平面阴影", "动画", "游戏", "toon", "bold"],
  },
  {
    slug: "wabi-sabi",
    name: "侘寂风",
    nameEn: "Wabi-Sabi",
    description: "日本侘寂美学的数字化呈现，崇尚不完美之美、自然衰老之雅和极致留白之禅，以墨色、茶色和纸张质感传递东方诗意。",
    cover: "/styles/wabi-sabi.jpg",
    styleType: "visual",
    tags: [],
    category: "minimal",
    colors: {
      primary: "#3a3a3a",
      secondary: "#f2ede4",
      accent: ["#8a9a7b", "#b5a78c", "#8b6f4e"],
    },
    keywords: ["侘寂", "日式", "禅", "不完美", "留白", "Ma", "纸张", "自然", "东方"],
  },
  {
    slug: "zen-garden",
    name: "枯山水",
    nameEn: "Zen Garden",
    description:
      "日本枯山水庭园的数字化诠释，以砂纹、石组、苔藓为灵感，追求极致静谧与冥想感。沙白与苔绿的搭配传递出自然之道的宁静力量。",
    cover: "/styles/zen-garden.svg",
    styleType: "visual",
    tags: [],
    category: "minimal",
    colors: {
      primary: "#4a5548",
      secondary: "#f5f3ee",
      accent: ["#8a9a7b", "#c4bba8", "#7a7062"],
    },
    keywords: ["枯山水", "日式", "禅", "砂纹", "石组", "苔藓", "冥想", "庭园", "karesansui"],
  },
  // New styles - Batch 9 (Competitive analysis)
  {
    slug: "sci-fi-hud",
    name: "科幻HUD",
    nameEn: "Sci-Fi HUD",
    description: "源自星际飞船驾驶舱和战术指挥中心的全息显示界面。深空背景、青色发光边框、半透明玻璃面板、雷达扫描动效，营造'正在操作高科技设备'的沉浸体验。",
    cover: "/styles/sci-fi-hud.svg",
    styleType: "visual",
    tags: ["high-contrast", "dark-theme", "game-ui"],
    category: "modern",
    colors: {
      primary: "#06B6D4",
      secondary: "#020617",
      accent: ["#0EA5E9", "#22D3EE", "#22C55E"],
    },
    keywords: ["科幻", "HUD", "全息", "雷达", "指挥中心", "太空", "发光边框", "数据流"],
  },
  {
    slug: "kawaii-minimal",
    name: "可爱极简",
    nameEn: "Kawaii Minimal",
    description: "融合日系可爱文化与极简设计的温柔风格。柔和的粉彩色系、圆润形状、轻盈留白和细腻的微交互，适合生活方式应用、儿童产品和创意工具。",
    cover: "/styles/kawaii-minimal.svg",
    styleType: "visual",
    tags: [],
    category: "minimal",
    colors: {
      primary: "#F9A8D4",
      secondary: "#FFF7ED",
      accent: ["#A78BFA", "#67E8F9", "#FDE68A"],
    },
    keywords: ["可爱", "极简", "粉彩", "圆润", "温柔", "日系", "卡哇伊"],
  },
  {
    slug: "film-noir",
    name: "黑色电影",
    nameEn: "Film Noir",
    description: "源自 1940-50 年代经典黑色电影的戏剧性视觉风格。极致的明暗对比、深沉的灰阶层次、斜线光影和神秘氛围，适合故事驱动的产品、摄影作品集和高端品牌。",
    cover: "/styles/film-noir.svg",
    styleType: "visual",
    tags: ["high-contrast", "dark-theme"],
    category: "retro",
    colors: {
      primary: "#1a1a1a",
      secondary: "#f5f5f0",
      accent: ["#c41e3a", "#8b7355", "#d4af37"],
    },
    keywords: ["黑色电影", "明暗对比", "光影", "戏剧", "复古", "神秘", "高对比"],
  },
  // New styles - Batch 10
  {
    slug: "arcade-crt",
    name: "街机CRT",
    nameEn: "Arcade CRT",
    description: "80-90年代街机显示器美学，包含扫描线、屏幕曲率、霓虹辉光和RGB色差效果。适合游戏、复古科技、创意项目。",
    cover: "/styles/arcade-crt.svg",
    styleType: "visual",
    tags: ["retro", "high-contrast", "dark-theme", "game-ui"],
    category: "retro",
    colors: {
      primary: "#39ff14",
      secondary: "#050505",
      accent: ["#ff00ff", "#00ffff", "#ff2a2a", "#FFFF00", "#ff8533"],
    },
    keywords: ["CRT", "扫描线", "复古游戏", "街机", "像素", "霓虹", "色差"],
  },
  {
    slug: "frutiger-aero",
    name: "Frutiger Aero",
    nameEn: "Frutiger Aero",
    description: "Windows Vista/7时代的玻璃质感美学，天空蓝渐变、半透明毛玻璃面板与自然元素融合，营造清新通透的数字自然感。",
    cover: "/styles/frutiger-aero.svg",
    styleType: "visual",
    tags: ["retro"],
    category: "retro",
    colors: {
      primary: "#87CEEB",
      secondary: "#5FB3CC",
      accent: ["#ffffff", "#e0f2fe", "#34d399", "#7dd3fc"],
    },
    keywords: ["aero glass", "translucent", "sky blue", "glossy", "Vista", "Y2K", "nature", "bubbles"],
  },
  {
    slug: "anti-design",
    name: "反设计",
    nameEn: "Anti-Design",
    description: "故意打破传统UI规范的粗野主义实验风格，极粗边框、高饱和色彩、不规则排版和刻意的不协调感。源自朋克精神与实验艺术，拒绝装饰、强调原始信息传达。",
    cover: "/styles/anti-design.svg",
    styleType: "visual",
    tags: ["high-contrast"],
    category: "expressive",
    colors: {
      primary: "#000000",
      secondary: "#FFFFFF",
      accent: ["#FF0000", "#0000FF", "#FFFF00", "#FF00FF", "#00FFFF", "#00FF00"],
    },
    keywords: ["brutalism", "anti-design", "raw", "experimental", "bold", "punk", "rebellious"],
  },
  // New styles - Batch 11
  {
    slug: "holographic",
    name: "全息渐变",
    nameEn: "Holographic",
    description: "彩虹光谱虹彩渐变美学，模拟全息投影的棱镜折射与动态光效，营造超凡脱俗的虹彩体验。",
    cover: "/styles/holographic.svg",
    styleType: "visual",
    tags: ["high-contrast", "dark-theme", "colorful", "gradient"],
    category: "expressive",
    colors: {
      primary: "#a855f7",
      secondary: "#0a0a1f",
      accent: ["#ff0080", "#ffd700", "#00d4ff", "#00ff88", "#6366f1"],
    },
    keywords: ["holographic", "iridescent", "rainbow", "prismatic", "gradient", "spectrum", "foil", "全息", "虹彩", "棱镜"],
  },
  {
    slug: "generative-art",
    name: "生成艺术",
    nameEn: "Generative Art",
    description: "算法驱动的程序化视觉美学，以数学函数、噪声纹理和参数化图形创造独特动态界面。适合创意编程、数据可视化、艺术项目。",
    cover: "/styles/generative-art.svg",
    styleType: "visual",
    tags: ["high-contrast"],
    category: "expressive",
    colors: {
      primary: "#7c3aed",
      secondary: "#0a0a0a",
      accent: ["#3b82f6", "#14b8a6", "#f43f5e", "#f59e0b"],
    },
    keywords: ["generative", "algorithmic", "procedural", "noise", "particles", "fractal", "code art", "creative coding", "生成艺术", "算法", "程序化"],
  },
  {
    slug: "particle",
    name: "粒子系统",
    nameEn: "Particle System",
    description: "深色科技背景上漂浮的粒子网络，以连线、脉冲和轨迹营造数据流动感。适合科技公司、数据可视化、创意作品集。",
    cover: "/styles/particle.svg",
    styleType: "visual",
    tags: ["dark-theme"],
    category: "modern",
    colors: {
      primary: "#0a0e1a",
      secondary: "#0f1419",
      accent: ["#e0e8ff", "#64c8ff", "#64ffc8", "#a78bfa"],
    },
    keywords: ["particles", "network", "connections", "floating", "tech", "nodes", "constellation"],
  },
  {
    slug: "vhs-aesthetic",
    name: "VHS美学",
    nameEn: "VHS Aesthetic",
    description: "80-90年代VHS录像带视觉美学，色彩失真、扫描线噪点、信号故障效果和磁带抖动。以模拟信号损坏的怀旧质感唤起家庭录像和地下音乐的记忆。",
    cover: "/styles/vhs-aesthetic.svg",
    styleType: "visual",
    tags: ["retro", "high-contrast", "dark-theme", "texture-heavy"],
    category: "retro",
    colors: {
      primary: "#ff00ff",
      secondary: "#000000",
      accent: ["#00ffff", "#ff0066", "#ffff00", "#6600ff"],
    },
    keywords: ["vhs", "retro", "glitch", "scanlines", "nostalgia", "80s", "cassette", "analog"],
  },
  // New styles - Batch 12 (Quality & category balance)
  {
    slug: "ink-wash",
    name: "水墨画风",
    nameEn: "Ink Wash",
    description: "源自中国传统水墨画的设计风格，以墨色浓淡干湿变化营造空灵意境，大量留白表达'气韵生动'，适合文化品牌、茶道、书法和东方美学项目。",
    cover: "/styles/ink-wash.svg",
    styleType: "visual",
    tags: [],
    category: "minimal",
    colors: {
      primary: "#2c2c2c",
      secondary: "#f8f5f0",
      accent: ["#6b7b6e", "#a89279", "#c4b9a8"],
    },
    keywords: ["水墨", "国画", "留白", "意境", "东方", "书法", "文化", "气韵"],
  },
  {
    slug: "monochrome",
    name: "单色极简",
    nameEn: "Monochrome",
    description: "纯黑白灰的极致单色设计，通过精确的灰阶层次、字重对比和负空间构建视觉层次，不依赖任何色彩即达到高级感。适合摄影、建筑和高端品牌。",
    cover: "/styles/monochrome.svg",
    styleType: "visual",
    tags: ["high-contrast"],
    category: "minimal",
    colors: {
      primary: "#111111",
      secondary: "#fafafa",
      accent: ["#666666", "#999999", "#cccccc"],
    },
    keywords: ["单色", "黑白", "灰阶", "极简", "无色彩", "高级感", "摄影", "建筑"],
  },
  {
    slug: "terracotta",
    name: "赤陶暖调",
    nameEn: "Terracotta",
    description: "地中海赤陶与暖色大地的设计风格，温暖的陶土色调、粗糙手工质感和自然纹理。适合生活方式品牌、餐饮、旅行和手工艺品展示。",
    cover: "/styles/terracotta.svg",
    styleType: "visual",
    tags: [],
    category: "minimal",
    colors: {
      primary: "#b5654a",
      secondary: "#faf5ef",
      accent: ["#d4a373", "#7a6350", "#8b9d77"],
    },
    keywords: ["赤陶", "大地色", "地中海", "暖调", "手工", "陶土", "自然", "温暖"],
  },
  {
    slug: "brutalist-web",
    name: "网页粗野主义",
    nameEn: "Brutalist Web",
    description: "90年代早期互联网的原始美学回归，系统字体、无样式链接、裸露的HTML结构感和刻意的低保真。以最少的装饰传达最直接的内容，是对过度设计的反思。",
    cover: "/styles/brutalist-web.svg",
    styleType: "visual",
    tags: ["retro", "high-contrast"],
    category: "minimal",
    colors: {
      primary: "#000000",
      secondary: "#ffffff",
      accent: ["#0000ff", "#ff0000", "#008000"],
    },
    keywords: ["粗野主义", "原始", "低保真", "系统字体", "90年代", "反设计", "内容优先"],
  },
  // New styles - Batch 13 (Cultural + Art movements)
  {
    slug: "mid-century-modern",
    name: "中世纪现代",
    nameEn: "Mid-Century Modern",
    description: "50年代原子时代设计美学，几何图案、有机曲线、饱和色彩。Eames椅、原子钟、星芒图案为灵感。",
    cover: "/styles/mid-century-modern.svg",
    styleType: "visual",
    tags: ["retro", "geometric"],
    category: "retro",
    colors: {
      primary: "#e8572a",
      secondary: "#f5f0e1",
      accent: ["#2a6e5e", "#c4a35a", "#3d3d3d"],
    },
    keywords: ["中世纪", "原子时代", "有机曲线", "星芒", "复古现代"],
  },
  {
    slug: "constructivism",
    name: "构成主义",
    nameEn: "Constructivism",
    description: "苏联构成主义海报风格，强烈的红黑配色、对角线构图、几何块面、宣传性排版。",
    cover: "/styles/constructivism.svg",
    styleType: "visual",
    tags: ["retro", "high-contrast", "colorful", "geometric"],
    category: "retro",
    colors: {
      primary: "#cc0000",
      secondary: "#f2e8d5",
      accent: ["#1a1a1a", "#d4a843", "#8b4513"],
    },
    keywords: ["构成主义", "苏联", "海报", "几何", "宣传", "对角线"],
  },
  {
    slug: "op-art",
    name: "欧普艺术",
    nameEn: "Op Art",
    description: "光学艺术运动风格，利用几何图案制造视觉幻象和运动感。黑白对比为核心，辅以振动色彩对。",
    cover: "/styles/op-art.svg",
    styleType: "visual",
    tags: ["high-contrast", "geometric"],
    category: "expressive",
    colors: {
      primary: "#000000",
      secondary: "#ffffff",
      accent: ["#ff3300", "#0066ff", "#ffcc00"],
    },
    keywords: ["光学", "幻觉", "视觉", "运动感", "几何", "黑白", "振动"],
  },
  {
    slug: "islamic-geometric",
    name: "伊斯兰几何",
    nameEn: "Islamic Geometric",
    description: "伊斯兰几何纹理设计风格，精密的几何镶嵌图案、阿拉伯式花纹、金色与深蓝的经典配色。",
    cover: "/styles/islamic-geometric.svg",
    styleType: "visual",
    tags: ["geometric", "texture-heavy"],
    category: "expressive",
    colors: {
      primary: "#1a3a5c",
      secondary: "#f5ecd7",
      accent: ["#c9a74e", "#2d7d46", "#8b2332"],
    },
    keywords: ["伊斯兰", "几何", "镶嵌", "阿拉伯", "花纹", "纹理"],
  },
  {
    slug: "indian-festive",
    name: "印度节庆",
    nameEn: "Indian Festive",
    description: "印度排灯节与色彩节的绚丽美学，丰富的金色装饰、宝石色调、曼荼罗纹饰。适合庆典、活动、生活方式品牌。",
    cover: "/styles/indian-festive.svg",
    styleType: "visual",
    tags: ["high-contrast", "colorful", "texture-heavy"],
    category: "expressive",
    colors: {
      primary: "#e63946",
      secondary: "#fff8e7",
      accent: ["#ff9f1c", "#7b2d8e", "#2a9d8f", "#d4af37"],
    },
    keywords: ["印度", "排灯节", "色彩节", "曼荼罗", "金色", "宝石色", "节庆"],
  },
  {
    slug: "african-textile",
    name: "非洲纺织",
    nameEn: "African Textile",
    description: "西非Kente布和Adire扎染为灵感的设计风格，大胆的几何编织图案、大地色与鲜明色彩的碰撞、手工质感。",
    cover: "/styles/african-textile.svg",
    styleType: "visual",
    tags: ["high-contrast", "colorful", "texture-heavy"],
    category: "expressive",
    colors: {
      primary: "#c4501f",
      secondary: "#2c1810",
      accent: ["#f0c75e", "#1a5632", "#e8d5b5"],
    },
    keywords: ["非洲", "Kente", "编织", "扎染", "纺织", "大地", "手工"],
  },
  {
    slug: "korean-minimal",
    name: "韩式极简",
    nameEn: "Korean Minimal",
    description: "韩国极简设计美学，受K-beauty和韩国建筑影响。柔和的粉彩色调、大量留白、精致的圆角和克制的装饰。",
    cover: "/styles/korean-minimal.svg",
    styleType: "visual",
    tags: [],
    category: "minimal",
    colors: {
      primary: "#3d4a5c",
      secondary: "#faf9f7",
      accent: ["#d4a5a5", "#a8c5b8", "#e8d4b8"],
    },
    keywords: ["韩式", "极简", "K-beauty", "留白", "粉彩", "克制", "精致"],
  },
  {
    slug: "pastel-goth",
    name: "粉彩哥特",
    nameEn: "Pastel Goth",
    description: "柔暗美学与糖果色的独特融合，粉紫粉蓝等柔和色彩搭配骷髅、十字架等暗系元素。暗色背景+粉彩高亮。",
    cover: "/styles/pastel-goth.svg",
    styleType: "visual",
    tags: ["high-contrast", "dark-theme"],
    category: "expressive",
    colors: {
      primary: "#2d1b3d",
      secondary: "#1a1225",
      accent: ["#d4a5e3", "#7ec8c8", "#f5a5b8", "#b8a5f5"],
    },
    keywords: ["粉彩哥特", "柔暗", "糖果色", "骷髅", "十字架", "暗色", "粉紫"],
  },
  {
    slug: "maximalism",
    name: "极繁主义",
    nameEn: "Maximalism",
    description: "极繁主义设计——更多就是更多。层叠图案、混搭字体、饱和色彩、装饰性边框。拥抱丰富、华丽和视觉冲击。",
    cover: "/styles/maximalism.svg",
    styleType: "visual",
    tags: ["high-contrast", "colorful", "texture-heavy"],
    category: "expressive",
    colors: {
      primary: "#d4145a",
      secondary: "#1a0a2e",
      accent: ["#ffbe0b", "#3a86ff", "#8338ec", "#06d6a0"],
    },
    keywords: ["极繁", "华丽", "层叠", "混搭", "饱和", "装饰", "丰富"],
  },
  {
    slug: "medieval-manuscript",
    name: "中世纪手抄本",
    nameEn: "Medieval Manuscript",
    description: "中世纪泥金手抄本风格，花体首字母、羊皮纸质感、金色与深红装饰性边框。哥特式黑体字与插画元素。",
    cover: "/styles/medieval-manuscript.svg",
    styleType: "visual",
    tags: ["retro", "texture-heavy"],
    category: "retro",
    colors: {
      primary: "#8b1a1a",
      secondary: "#f0e6d0",
      accent: ["#c9a74e", "#2d4a2d", "#3d2b1f"],
    },
    keywords: ["中世纪", "手抄本", "泥金", "花体", "羊皮纸", "哥特字体", "装饰"],
  },
  {
    slug: "graffiti-street",
    name: "涂鸦街头",
    nameEn: "Graffiti Street",
    description: "街头涂鸦艺术风格，喷漆质感、大胆的撞色、手写体标签、砖墙背景。都市文化与反叛精神的视觉表达。",
    cover: "/styles/graffiti-street.svg",
    styleType: "visual",
    tags: ["high-contrast", "texture-heavy"],
    category: "expressive",
    colors: {
      primary: "#ff2d55",
      secondary: "#1c1c1e",
      accent: ["#00e5ff", "#ffea00", "#b620e0", "#ff6d00"],
    },
    keywords: ["涂鸦", "街头", "喷漆", "撞色", "都市", "反叛", "标签"],
  },
  {
    slug: "marble-luxury",
    name: "大理石奢华",
    nameEn: "Marble Luxury",
    description: "大理石纹理与金色装饰的高端设计风格，白色大理石质感背景、金色线条分隔、黑色文字。适合奢侈品牌、酒店。",
    cover: "/styles/marble-luxury.svg",
    styleType: "visual",
    tags: [],
    category: "modern",
    colors: {
      primary: "#1a1a1a",
      secondary: "#f8f6f3",
      accent: ["#c9a96e", "#8a7968", "#e8e0d6"],
    },
    keywords: ["大理石", "奢华", "金色", "高端", "纹理", "精致", "品牌"],
  },
  {
    slug: "victorian-botanical",
    name: "维多利亚植物",
    nameEn: "Victorian Botanical",
    description: "维多利亚时代植物学插画风格，精细的线描植物、花卉纹饰、自然历史博物馆的优雅。暗绿与金色的经典搭配。",
    cover: "/styles/victorian-botanical.svg",
    styleType: "visual",
    tags: ["retro", "texture-heavy"],
    category: "retro",
    colors: {
      primary: "#2d4a2d",
      secondary: "#faf5ef",
      accent: ["#8b6914", "#6b3a3a", "#3d5c3d"],
    },
    keywords: ["维多利亚", "植物", "插画", "花卉", "自然", "线描", "博物馆"],
  },
  {
    slug: "cubism",
    name: "立体主义",
    nameEn: "Cubism",
    description: "毕加索和布拉克的立体主义运动，几何碎片化构图、多视角叠加、棱角分明的形状与沉稳的大地色调。",
    cover: "/styles/cubism.svg",
    styleType: "visual",
    tags: ["retro"],
    category: "expressive",
    colors: {
      primary: "#5c4033",
      secondary: "#e8dcc8",
      accent: ["#8b7355", "#3d5c6e", "#9b3d25"],
    },
    keywords: ["立体主义", "毕加索", "几何", "碎片", "多视角", "棱角", "大地色"],
  },
  {
    slug: "tropical-paradise",
    name: "热带天堂",
    nameEn: "Tropical Paradise",
    description: "热带度假风设计，棕榈叶、鲜艳花卉色彩、阳光沙滩的明快基调。适合旅游、度假村、生活方式和餐饮品牌。",
    cover: "/styles/tropical-paradise.svg",
    styleType: "visual",
    tags: ["colorful"],
    category: "modern",
    colors: {
      primary: "#00897b",
      secondary: "#fffde7",
      accent: ["#ff6f61", "#ffc107", "#4caf50"],
    },
    keywords: ["热带", "天堂", "棕榈", "花卉", "阳光", "度假", "明快"],
  },
  {
    slug: "github-style",
    name: "GitHub 风格",
    nameEn: "GitHub Style",
    description: "GitHub设计语言风格，简洁的界面层次、柔和的灰度系统、蓝色交互色、等宽代码字体与开发者友好的信息架构。",
    cover: "/styles/github-style.svg",
    styleType: "visual",
    tags: ["brand-inspired"],
    category: "modern",
    colors: {
      primary: "#0969da",
      secondary: "#ffffff",
      accent: ["#1f883d", "#9a6700", "#cf222e"],
    },
    keywords: ["GitHub", "开发者", "代码", "简洁", "灰度", "蓝色", "设计系统"],
  },
  {
    slug: "witchcore",
    name: "巫术核心",
    nameEn: "Witchcore",
    description: "神秘学美学风格，塔罗牌、月相符号、水晶与草药元素。深紫色调搭配金色神秘符文，暗色背景上闪烁的星尘效果。",
    cover: "/styles/witchcore.svg",
    styleType: "visual",
    tags: ["high-contrast", "dark-theme"],
    category: "expressive",
    colors: {
      primary: "#4a1942",
      secondary: "#0d0b14",
      accent: ["#c9a74e", "#7b68ae", "#3d8b6e"],
    },
    keywords: ["巫术", "神秘", "塔罗", "月相", "水晶", "符文", "暗黑"],
  },
  {
    slug: "neon-tokyo",
    name: "霓虹东京",
    nameEn: "Neon Tokyo",
    description: "东京歌舞伎町霓虹夜景风格，湿润的街道倒影、叠层霓虹招牌、赛博朋克城市夜色。偏向真实都市夜景质感。",
    cover: "/styles/neon-tokyo.svg",
    styleType: "visual",
    tags: ["high-contrast", "dark-theme", "gradient"],
    category: "modern",
    colors: {
      primary: "#ff1493",
      secondary: "#0a0a1a",
      accent: ["#00f0ff", "#ff6b00", "#bc13fe"],
    },
    keywords: ["霓虹", "东京", "夜景", "歌舞伎町", "都市", "招牌", "倒影"],
  },
  {
    slug: "paper-craft",
    name: "纸艺手作",
    nameEn: "Paper Craft",
    description: "纸艺与剪纸风格，层叠纸张效果、柔和阴影暗示深度、手作质感边缘。适合儿童品牌、教育产品、创意工作室。",
    cover: "/styles/paper-craft.svg",
    styleType: "visual",
    tags: ["hand-drawn"],
    category: "expressive",
    colors: {
      primary: "#e85d75",
      secondary: "#fdf6ee",
      accent: ["#5cb8a5", "#f5c040", "#6b7fb5"],
    },
    keywords: ["纸艺", "剪纸", "手作", "层叠", "阴影", "创意", "质感"],
  },
  {
    slug: "blueprint",
    name: "工程蓝图",
    nameEn: "Blueprint",
    description: "工程蓝图与技术图纸风格，蓝底白线、网格坐标、标注线和尺寸标记。适合建筑、工程、科技和教育领域。",
    cover: "/styles/blueprint.svg",
    styleType: "visual",
    tags: [],
    category: "minimal",
    colors: {
      primary: "#ffffff",
      secondary: "#1e3a5f",
      accent: ["#4a90d9", "#ff6b35", "#a0c4e8"],
    },
    keywords: ["蓝图", "工程", "技术", "图纸", "网格", "标注", "坐标"],
  },
  {
    slug: "dopamine-design",
    name: "多巴胺设计",
    nameEn: "Dopamine Design",
    description: "高饱和度霓虹配色、大胆排版、充满能量感的视觉冲击力。2025-2026 年度设计趋势，用色彩直接刺激多巴胺分泌。",
    cover: "/styles/dopamine-design.svg",
    styleType: "visual",
    tags: ["high-contrast", "colorful"],
    category: "expressive",
    colors: {
      primary: "#ff006e",
      secondary: "#8338ec",
      accent: ["#ffbe0b", "#3a86ff", "#06d6a0", "#fb5607"],
    },
    keywords: ["多巴胺", "高饱和", "霓虹", "快乐", "大胆", "能量"],
  },
  {
    slug: "linear-style",
    name: "Linear 风格",
    nameEn: "Linear Style",
    description: "受 Linear 应用启发的极简暗色设计风格。精确的排版、克制的动效、开发者审美的极致表达。",
    cover: "/styles/linear-style.svg",
    styleType: "visual",
    tags: ["dark-theme"],
    category: "minimal",
    colors: {
      primary: "#5e6ad2",
      secondary: "#0a0a0b",
      accent: ["#f2c94c", "#27ae60", "#eb5757", "#2d9cdb"],
    },
    keywords: ["Linear", "极简", "暗色", "开发者", "精确", "工具"],
  },
  // Batch 15 - Scenario Gap Fill
  {
    slug: "shopify-clean",
    name: "清爽电商",
    nameEn: "Shopify Clean",
    description: "面向独立电商站的干净现代风格，以产品为核心，清晰的价格层级和流畅的购物转化路径。",
    cover: "/styles/shopify-clean.svg",
    styleType: "visual",
    tags: ["brand-inspired"],
    category: "modern",
    colors: {
      primary: "#ffffff",
      secondary: "#f7f7f8",
      accent: ["#008060", "#1a1a1a", "#e3e3e3", "#ffd700"],
    },
    keywords: ["电商", "独立站", "产品展示", "购物车", "DTC", "Shopify"],
  },
  {
    slug: "luxury-retail",
    name: "奢品零售",
    nameEn: "Luxury Retail",
    description: "高端零售与奢侈品牌风格，大面积留白搭配衬线字体，金色与大理石质感传递尊贵感。",
    cover: "/styles/luxury-retail.svg",
    styleType: "visual",
    tags: [],
    category: "modern",
    colors: {
      primary: "#faf9f6",
      secondary: "#1a1a1a",
      accent: ["#c9a96e", "#8b7355", "#e8e0d4", "#2c2c2c"],
    },
    keywords: ["奢侈品", "高端", "品牌", "零售", "大留白", "衬线"],
  },
  {
    slug: "fresh-market",
    name: "鲜活市集",
    nameEn: "Fresh Market",
    description: "面向食品生鲜与有机品牌的电商风格，暖色调圆润卡片搭配自然纹理，传递新鲜与信任。",
    cover: "/styles/fresh-market.svg",
    styleType: "visual",
    tags: [],
    category: "modern",
    colors: {
      primary: "#fef9f0",
      secondary: "#2d5016",
      accent: ["#e8722a", "#f5c542", "#8b4513", "#d4e4bc"],
    },
    keywords: ["生鲜", "食品", "有机", "电商", "暖色", "自然"],
  },
  {
    slug: "data-dense",
    name: "数据密集",
    nameEn: "Data Dense",
    description: "高密度后台管理面板风格，紧凑间距与小尺寸组件，优先展示数据表格与操作效率。",
    cover: "/styles/data-dense.svg",
    styleType: "visual",
    tags: ["dark-theme", "responsive"],
    category: "modern",
    colors: {
      primary: "#ffffff",
      secondary: "#f8fafc",
      accent: ["#3b82f6", "#ef4444", "#22c55e", "#64748b"],
    },
    keywords: ["后台管理", "数据表格", "高密度", "管理面板", "运营", "admin"],
  },
  // Batch 16 (Portfolio + Academic)
  {
    slug: "oversized-typography",
    name: "超大字体排版",
    nameEn: "Oversized Typography",
    description: "2026 年作品集网站头号趋势——文字即布局。姓名与标题以视口级 fluid clamp() 巨字充当 hero 和视觉主体，图像退居次要，黑白底色配唯一国际橙强调。",
    cover: "/styles/oversized-typography.svg",
    styleType: "visual",
    tags: ["high-contrast"],
    category: "expressive",
    colors: {
      primary: "#0A0A0A",
      secondary: "#FAFAF8",
      accent: ["#FF4D00", "#71717A", "#E4E4E7", "#18181B"],
    },
    keywords: ["超大字体", "巨字排版", "作品集", "fluid typography", "clamp", "marquee"],
  },
  {
    slug: "developer-terminal",
    name: "终端风",
    nameEn: "Developer Terminal",
    description: "把网站做成一场终端会话：荧光绿 mono 文字、prompt 前缀、命令与输出的成对结构、tmux 状态栏，用工具的真实感表达开发者身份。",
    cover: "/styles/developer-terminal.svg",
    styleType: "visual",
    tags: ["high-contrast", "dark-theme"],
    category: "modern",
    colors: {
      primary: "#4AF626",
      secondary: "#0A0E12",
      accent: ["#8BE9FD", "#FF79C6", "#FFB86C", "#6272A4"],
    },
    keywords: ["终端", "命令行", "CLI", "开发者", "等宽字体", "terminal"],
  },
  {
    slug: "horizontal-gallery",
    name: "横滚画廊",
    nameEn: "Horizontal Gallery",
    description: "白盒美术馆式的横向滚动作品集布局，无边框大图沿水平展线依次排开，留白即展墙，编号与极细图注还原策展语言，观看是一场步行。",
    cover: "/styles/horizontal-gallery.svg",
    styleType: "layout",
    tags: ["responsive"],
    category: "minimal",
    colors: {
      primary: "#1A1A1A",
      secondary: "#FCFCFA",
      accent: ["#A85A3A", "#8A8A85", "#E8E6E1", "#2E2E2C"],
    },
    keywords: ["横滚", "画廊", "策展", "白盒", "作品集", "留白"],
  },
  {
    slug: "latex-paper",
    name: "论文排版风",
    nameEn: "LaTeX Paper",
    description: "把 LaTeX 学术论文的排版语言搬到网页：Computer Modern 字感、居中标题与 Abstract、层级编号小节、定理环境、编号公式、booktabs 表格与悬挂缩进参考文献。适合研究主页、课程讲义与学术型作品集。",
    cover: "/styles/latex-paper.svg",
    styleType: "visual",
    tags: ["retro", "high-contrast"],
    category: "minimal",
    colors: {
      primary: "#111111",
      secondary: "#FFFFFF",
      accent: ["#0B5394", "#F5F5F0", "#6B6B66", "#D4D4D0"],
    },
    keywords: ["学术", "论文", "LaTeX", "排版", "定理环境", "编号公式", "booktabs", "参考文献"],
  },
  {
    slug: "distill-style",
    name: "学术科普风",
    nameEn: "Distill Style",
    description: "以 Distill.pub 为原型的学术科普设计语言：窄列 serif 正文承载论证，边注承载旁白，图表突破版心承载证据。适合科普博客、研究者主页与学术型作品集。",
    cover: "/styles/distill-style.svg",
    styleType: "visual",
    tags: ["brand-inspired"],
    category: "minimal",
    colors: {
      primary: "#1F2933",
      secondary: "#FFFFFF",
      accent: ["#2A7AE2", "#E4572E", "#6B7280", "#F3F4F6"],
    },
    keywords: ["学术", "科普", "边注", "引用", "图表", "衬线正文", "研究者主页", "Distill"],
  },
];
