// shadcn/ui Theme Generator
// Derives each style's real design tokens (colors, radius, borders) into the
// raw CSS values a shadcn theme needs, so every style yields a distinct theme.

import type { DesignStyle } from "../styles";
import { getStyleTokens } from "../styles/tokens-registry";
import {
  colorToHsl,
  hslLightness,
  resolveTwColor,
  twRadiusToRem,
} from "./color-resolve";

export interface ShadcnTheme {
  name: string;
  cssVars: {
    light: Record<string, string>;
    dark: Record<string, string>;
  };
}

// Neutral shadcn defaults, used only when a style token cannot be resolved.
const FALLBACK = {
  lightBg: "0 0% 100%",
  lightFg: "0 0% 3.9%",
  lightMuted: "0 0% 96.1%",
  lightMutedFg: "0 0% 45.1%",
  lightBorder: "0 0% 89.8%",
  darkBg: "0 0% 3.9%",
  darkFg: "0 0% 98%",
  darkMuted: "0 0% 14.9%",
  darkMutedFg: "0 0% 63.9%",
  darkBorder: "0 0% 14.9%",
  primary: "0 0% 9%",
  radius: "0.5rem",
};

/** Resolve a value that may be a raw color (hex/rgba/oklch) OR a Tailwind class. */
function anyColorToHsl(input?: string): string | null {
  if (!input) return null;
  return colorToHsl(input) ?? resolveTwColor(input);
}

/** Pick a readable near-black / near-white foreground for a given HSL background. */
function readableForeground(hslBg: string): string {
  const l = hslLightness(hslBg);
  if (l === null) return "0 0% 98%";
  return l >= 55 ? "0 0% 9%" : "0 0% 98%";
}

export function generateShadcnTheme(style: DesignStyle): ShadcnTheme {
  const tokens = getStyleTokens(style.slug);

  // Structural colors derived from the style's semantic tokens.
  const bg =
    (tokens && resolveTwColor(tokens.colors.background.primary)) ??
    FALLBACK.lightBg;
  const fg =
    (tokens && resolveTwColor(tokens.colors.text.primary)) ?? FALLBACK.lightFg;
  const muted =
    (tokens && resolveTwColor(tokens.colors.background.secondary)) ??
    FALLBACK.lightMuted;
  const mutedFg =
    (tokens && resolveTwColor(tokens.colors.text.muted)) ??
    FALLBACK.lightMutedFg;
  const border =
    (tokens && resolveTwColor(tokens.border.color)) ?? FALLBACK.lightBorder;
  const radius =
    (tokens && twRadiusToRem(tokens.border.radius)) ?? FALLBACK.radius;

  // Brand colors from the style palette (robust across hex / rgba / class).
  const primary = anyColorToHsl(style.colors.primary) ?? FALLBACK.primary;
  const secondary = anyColorToHsl(style.colors.secondary) ?? muted;
  const accent = anyColorToHsl(style.colors.accent?.[0]) ?? primary;

  const light: Record<string, string> = {
    background: bg,
    foreground: fg,
    card: bg,
    "card-foreground": fg,
    popover: bg,
    "popover-foreground": fg,
    primary,
    "primary-foreground": readableForeground(primary),
    secondary,
    "secondary-foreground": readableForeground(secondary),
    muted,
    "muted-foreground": mutedFg,
    accent,
    "accent-foreground": readableForeground(accent),
    destructive: "0 72% 51%",
    "destructive-foreground": "0 0% 98%",
    border,
    input: border,
    ring: primary,
    radius,
  };

  // Dark mode keeps brand colors + radius over a neutral dark skeleton.
  const dark: Record<string, string> = {
    background: FALLBACK.darkBg,
    foreground: FALLBACK.darkFg,
    card: FALLBACK.darkBg,
    "card-foreground": FALLBACK.darkFg,
    popover: FALLBACK.darkBg,
    "popover-foreground": FALLBACK.darkFg,
    primary,
    "primary-foreground": readableForeground(primary),
    secondary,
    "secondary-foreground": readableForeground(secondary),
    muted: FALLBACK.darkMuted,
    "muted-foreground": FALLBACK.darkMutedFg,
    accent,
    "accent-foreground": readableForeground(accent),
    destructive: "0 62.8% 30.6%",
    "destructive-foreground": "0 0% 98%",
    border: FALLBACK.darkBorder,
    input: FALLBACK.darkBorder,
    ring: primary,
    radius,
  };

  return { name: style.slug, cssVars: { light, dark } };
}

export function generateShadcnThemeJSON(style: DesignStyle): string {
  return JSON.stringify(generateShadcnTheme(style), null, 2);
}

export function generateShadcnThemeCSS(style: DesignStyle): string {
  const theme = generateShadcnTheme(style);

  const lightVars = Object.entries(theme.cssVars.light)
    .map(([key, value]) => `    --${key}: ${value};`)
    .join("\n");
  const darkVars = Object.entries(theme.cssVars.dark)
    .map(([key, value]) => `    --${key}: ${value};`)
    .join("\n");

  return `/* ${style.name} (${style.nameEn}) - shadcn/ui Theme */
/* Generated by StyleKit */

@layer base {
  :root {
${lightVars}
  }

  .dark {
${darkVars}
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
  }
}
`;
}
